version: '3.8'
services:
    oai-gnb:
        image: oaisoftwarealliance/oai-gnb:develop
        privileged: true
        container_name: rfsim5g-oai-gnb
        environment: 
            RFSIMULATOR: server
            USE_ADDITIONAL_OPTIONS: --sa -E --rfsim --log_config.global_log_options level,nocolor,time
        volumes:
            - ./ran-conf/gnb.conf:/opt/oai-gnb/etc/gnb.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.153
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    
    oai-nr-ue1:
        image: oaisoftwarealliance/oai-nr-ue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue1
        environment: 
            RFSIMULATOR: 192.168.70.153
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208950000000039 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        depends_on:
            - oai-gnb
        volumes:
            - ./ran-conf/nr-ue1.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.152
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
     ##### adding new ue1 with the same gnb 
    oai-nr-ue2:
        image: oaisoftwarealliance/oai-nr-ue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue2 ### modified au lieu de 1 --noS1 --sa
        environment: 
            RFSIMULATOR: 192.168.70.153
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208950000000040 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        depends_on:
            - oai-gnb
        volumes:
            - ./ran-conf/nr-ue2.conf:/opt/oai-nr-ue/etc/nr-ue.conf # to add the new ue TO POINT to a new file
        networks:
            public_net:
                ipv4_address: 192.168.70.154 #modified however i will keep the same value 
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
       ######     
    oai-nr-ue3:
        image: oaisoftwarealliance/oai-nr-ue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue3 ### modified au lieu de 1
        environment: 
            RFSIMULATOR: 192.168.70.153
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208950000000041 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        depends_on:
            - oai-gnb
        volumes:
            - ./ran-conf/nr-ue3.conf:/opt/oai-nr-ue/etc/nr-ue.conf # to add the new ue TO POINT to a new file
        networks:
            public_net:
                ipv4_address: 192.168.70.156 #modified however i will keep the same value 
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        external:
            name: demo-oai-public-net
    #public_net_access:
        #external:
            #name: oai-public-access
